get_filename_component(_llvm_mingw "${CMAKE_CURRENT_LIST_DIR}/../third_party/llvm-mingw" ABSOLUTE)
if(NOT EXISTS "${_llvm_mingw}/bin/x86_64-w64-mingw32-clang++")
  message(FATAL_ERROR
    "llvm-mingw not found at ${_llvm_mingw}. Unpack llvm-mingw there or install g++-mingw-w64-x86-64.")
endif()

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "${_llvm_mingw}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${_llvm_mingw}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${_llvm_mingw}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_AR "${_llvm_mingw}/bin/x86_64-w64-mingw32-ar")
set(CMAKE_RANLIB "${_llvm_mingw}/bin/x86_64-w64-mingw32-ranlib")
set(CMAKE_FIND_ROOT_PATH "${_llvm_mingw}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
